DadJokes/Models/ErrorViewModel.cs
namespace DadJokes.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DadJokes/Models/Joke.cs
using System.ComponentModel.DataAnnotations;

namespace DadJokes.Models
{
    public class Joke
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Question { get; set; }
        [Required]
        public string? Answer { get; set; }




    }
}

DadJokes/Controllers/HomeController.cs
using DadJokes.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DadJokes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DadJokes/Controllers/JokeController.cs
using DadJokes.Data;
using DadJokes.Models;
using Microsoft.AspNetCore.Mvc;

namespace DadJokes.Controllers
{
    public class JokeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public JokeController(ApplicationDbContext db) {
        _db = db;
        } 
        public IActionResult Index()
        {
            IEnumerable<Models.Joke> objList = _db.Joke;
            return View(objList);
        }
        //GET - Create
        public IActionResult Create()
        {
         return View();
        }
        //POST - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Joke obj)
        {
            if (ModelState.IsValid)
            {
                _db.Joke.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            else return View(obj);
        }
        //GET - Details
        public IActionResult Details(int id)
        {
            var obj = _db.Joke.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //GET - Search
        public IActionResult ShowSearchForm()
        {
            return View();
        }

        
        public IActionResult ShowSearchResult(string SearchPhrase)
        {
            var obj = _db.Joke.Where(j=>j.Question.Contains(SearchPhrase));
            if (obj == null)
            {
                return NotFound();
            }
            return View("Index",obj);
        }

        //GET - Edit
        public IActionResult Edit(int id) {
            var obj = _db.Joke.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);   
        }

        //POST - Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Joke obj)
        {
            if (ModelState.IsValid)
            {
                _db.Joke.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            else return View(obj);
        }

        //GET - Delete
        public IActionResult Delete(int id)
        {
            var obj = _db.Joke.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST - Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int id)
        {
            var obj = _db.Joke.Find(id);
            if (obj == null) {
                return NotFound();
            }
                _db.Joke.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
        }
    }
}

DadJokes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome!</h1>
   <div class="p-3">
    <h2>This is my website that I build to practice a simple CRUD web application structure on ASP.NET Core 7.</h2>
    </div>
    <h3>You can enjoy some jokes by clicking <a asp-controller="Joke" asp-action="Index">Jokes</a></h3>
</div>

DadJokes/Views/Joke/Create.cshtml
@model DadJokes.Models.Joke
<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Joke</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4 p-3">
                        <label asp-for="Question"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Question" class="form-control"/>
                        <span asp-validation-for="Question" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4 p-3">
                        <label asp-for="Answer"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Answer" class="form-control" />
                        <span asp-validation-for="Answer" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class=" col">
                            <input type="submit" class="btn btn-success w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-100"><i class="fa-solid fa-right-from-bracket"></i>Back to Jokes</a>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-4">
                @*Keep this empty*@
            </div>
        </div>
    </div>
</form>

DadJokes/Views/Joke/Delete.cshtml
@model DadJokes.Models.Joke
<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete the Joke</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4 p-3">
                        <label asp-for="Question"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Question" disabled class="form-control" />
                   
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4 p-3">
                        <label asp-for="Answer"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Answer" disabled class="form-control" />
                   
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class=" col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-100"><i class="fa-solid fa-right-from-bracket"></i>Back to Jokes</a>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-4">
                @*Keep this empty*@
            </div>
        </div>
    </div>
</form>

DadJokes/Views/Joke/Details.cshtml
@model DadJokes.Models.Joke
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Joke Details</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4 p-3">
                        <label asp-for="Question"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Question" disabled class="form-control" />
                  
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4 p-3">
                        <label asp-for="Answer"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Answer" disabled class="form-control" />
                       
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                      
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-50"><i class="fa-solid fa-right-from-bracket"></i>Back to Jokes</a>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-4">
                @*Keep this empty*@
            </div>
        </div>
    </div>

DadJokes/Views/Joke/Edit.cshtml
@model DadJokes.Models.Joke
<form method="post">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Update the Joke</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4 p-3">
                        <label asp-for="Question"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Question" class="form-control" />
                        <span asp-validation-for="Question" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4 p-3">
                        <label asp-for="Answer"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Answer" class="form-control" />
                        <span asp-validation-for="Answer" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class=" col">
                            <input type="submit" class="btn btn-success w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-100"><i class="fa-solid fa-right-from-bracket"></i>Back to Jokes</a>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-4">
                @*Keep this empty*@
            </div>
        </div>
    </div>
</form>

DadJokes/Views/Joke/Index.cshtml
@model IEnumerable<DadJokes.Models.Joke>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Jokes</h2> 
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Joke" asp-action="Create" class="btn btn-primary"><i class="fa-solid fa-plus"></i> &nbsp; Add a new joke</a>
            
        </div>
    </div>
</div>

<br />
@if (Model.Count() > 0)
{<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
                <th class="text-center">
                Question
            </th>
                <th class="text-center">
                Answer
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
            @foreach(var obj in Model)
            {
                <tr>
                    <td width="50%" class="text-center">@obj.Question</td>
                    <td width="35%" class="text-center">
                    <a asp-controller="Joke" asp-route-Id="@obj.Id" asp-action="Details" class="btn btn-primary mx-2">Show Answer</a>
                    </td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Joke" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2"><i class="fa-solid fa-pen-to-square"></i></a>
                            <a asp-controller="Joke" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2"><i class="fa-solid fa-trash"></i></a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}
else
{
<p>There is no joke to display.</p>    
}

DadJokes/Views/Joke/ShowSearchForm.cshtml
<form method="post" asp-action="ShowSearchResult">
    <div class="border p-3">
       
        <div class="form-group row">
            <h2 class="text-info pl-3">Search Joke</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4 p-3">
                        <label for="SearchPhrase"></label>
                    </div>
                    <div class="col-8">
                        <input name="SearchPhrase" class="form-control" />
                        
                    </div>
                
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class=" col">
                                <input type="submit" class="btn btn-success w-100" value="Search" />
                        </div>
                        <div class="col">
                            <a asp-controller="Home" asp-action="Index" class="btn btn-primary w-100"><i class="fa-solid fa-right-from-bracket"></i>Back to Home</a>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-4">
                @*Keep this empty*@
            </div>
        </div>
    </div>
</form>

DadJokes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DadJokes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DadJokes.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" asp-append-version="true"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Joke" asp-action="Index">Jokes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Joke" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DadJokes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>